name: 'Test'

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - 'macos-latest'
          - 'ubuntu-latest'
          - 'windows-latest'

    runs-on: '${{ matrix.platform }}'

    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # ratchet:actions/checkout@v7

      - uses: 'actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e' # ratchet:actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: 'Test'
        shell: 'bash'
        run: |-
          make test
