name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-go@v5'
        with:
          cache: false
          go-version-file: 'go.mod'

      - uses: 'golangci/golangci-lint-action@v4'
        with:
          version: 'v1.57.2'
          skip-cache: true

  test:
    strategy:
      matrix:
        platform:
          - 'macos-latest'
          - 'ubuntu-latest'
          - 'windows-latest'
      fail-fast: false

    runs-on: '${{ matrix.platform }}'

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-go@v5'
        with:
          cache: false
          go-version-file: 'go.mod'

      - shell: 'bash'
        run: |-
          go test \
            -count=1 \
            -race \
            -shuffle=on \
            -timeout=5m \
            -vet=all \
            ./...
